name: Lint

on: [push]

jobs:
  lint:
    name: Run linter
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: yarn install --dev --frozen-lockfile

      - name: Check code quality
        run: yarn lint
